name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build debug binary
        run: |
          CLANG_MODULE_CACHE_PATH=$PWD/.build/ModuleCache \
          SWIFTPM_MODULECACHE_OVERRIDE=$PWD/.build/ModuleCache \
          swift build --scratch-path .build/spm

      - name: Run tests
        run: |
          CLANG_MODULE_CACHE_PATH=$PWD/.build/ModuleCache \
          SWIFTPM_MODULECACHE_OVERRIDE=$PWD/.build/ModuleCache \
          swift test --scratch-path .build/spm
